//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成.
//     运行时版本:2.0.50727.8745
//
//     对此文件的更改可能会导致不正确的行为,并且如果
//     重新生成代码,这些更改将会丢失.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IServiceApi")]
public interface IServiceApi
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceApi/Api", ReplyAction="http://tempuri.org/IServiceApi/ApiResponse")]
    string Api(string Parameters);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IServiceApiChannel : IServiceApi, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class ServiceApiClient : System.ServiceModel.ClientBase<IServiceApi>, IServiceApi
{
    
    public ServiceApiClient()
    {
    }
    
    public ServiceApiClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ServiceApiClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceApiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceApiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string Api(string Parameters)
    {
        return base.Channel.Api(Parameters);
    }
}
